# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrC
alias mongod="/c/Program\ Files/MongoDB/Server/6.0/bin/mongod.exe"
alias mongo="/c/Program\ Files/MongoDB/Client/1.6.0/bin/mongosh.exe"
alias rs="source ~/.bash_profile"

function ob()
{
	cd ~;
	notepad .bash_profile
}

function sql()
{
	cd /c/Program\ Files/MySQL/MySQL\ Server\ 8.0/bin;
	start mysql.exe -uroot -p
}

alias ga="git add ."
alias gps="git push"
alias gpl="git pull"
alias gi="notepad .gitignore"

function dd()
{
	cd ~;
	cd C:/Users/chris/Desktop/Directories/
}

function gc()
{
	git commit -m $1;
}

function gb()
{
	git branch $1;
}

function gbd()
{
	git branch -D $1;
}

function gco()
{
	git checkout $1;
}

function gpush()
{ 
	ARG1=${1:-.}
	ARG2=${2:-"update commit"}
	git add $ARG1
	git commit -m "$ARG2"
	git push
}

function gpull()
{
	git checkout master
	git pull
	git checkout CMA
	git merge master
}